import os
import sys
import subprocess
import yaml
import logging
from pathlib import Path
import gc

# Add project root to path
project_root = str(Path(__file__).parents[4])
if project_root not in sys.path:
    sys.path.append(project_root)

from src.cloud.base_model.utils.logging_utils import setup_logger

logger = logging.getLogger(__name__)

def free_memory():
    """Implements aggressive garbage collection to prevent VRAM spikes across phases."""
    logger.info("🧹 Initiating deep memory sweep (gc.collect and torch.cuda.empty_cache)...")
    gc.collect()
    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            logger.info("  ↳ CUDA VRAM cache cleared.")
    except ImportError:
        pass

def generate_health_log(phase_name, log_filename):
    """Stub function. In reality, QA logs will be generated by the Pytest routines or directly inside the labelling/training loops."""
    pass

def run_phase(name, script_path, check_exists=None, force_retrain=True):
    """
    Executes a phase via subprocess. 
    If check_exists is provided and force_retrain is False, checks if the target file exists to skip the phase.
    """
    logger.info("="*60)
    logger.info(f"🚀 INICIANDO FASE: {name}")
    logger.info("="*60)
    
    if not force_retrain and check_exists:
        # Checkpoint logic
        target_path = Path(check_exists)
        if target_path.exists():
            logger.info(f"⏭️ CHECKPOINT ENCONTRADO: {target_path.name} ja existe. Pulando {name} (force_full_retrain=False).")
            return True
            
    env = os.environ.copy()
    env["QUIET_LOGGING"] = "1"
    
    try:
        subprocess.run([sys.executable, script_path], check=True, env=env)
        logger.info(f"✅ FASE CONCLUIDA: {name}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ FASE FALHOU: {name}. Command: {e.cmd}")
        return False

def main():
    setup_logger("run_manager", "")
    
    # Load config
    master_cfg_path = Path("src/cloud/base_model/configs/master_config.yaml")
    with open(master_cfg_path, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
        
    ctrl = config.get('pipeline_control', {})
    force_retrain = ctrl.get('force_full_retrain', True)
    skip_qa_on_fail = ctrl.get('skip_qa_on_failure', False)
    manage_gpu = ctrl.get('gpu_memory_management', True)
    paths = config.get('pipeline_paths', {})
    
    from src.cloud.base_model.utils.path_utils import get_drive_session_path, resolve_local_drive, get_labelled_dir
    mod_dir = resolve_local_drive(Path(get_drive_session_path("MODELOS", config)))
    best_base_model = str(mod_dir / paths.get('best_tcn_lstm_model', 'BASE_MODEL/best_tcn_lstm.pt'))
    best_spec_model = str(mod_dir / paths.get('best_specialized_model', 'BASE_MODEL/test.pt'))
    auditor_model   = str(mod_dir / paths.get('auditor_model', 'AUDITOR/auditor_xgboost.json'))
    
    # QA logs Directory Generation
    qa_path = Path("logs/QA")
    qa_path.mkdir(parents=True, exist_ok=True)
    
    opt_cfg = config.get('optimization', {})
    search_space = opt_cfg.get('search_space', {})
    n_trials_base = opt_cfg.get('n_trials', 100)
    epochs = search_space.get('epochs', 50)
    patience = search_space.get('early_stopping_patience', 4)
    
    # ── FASE 0: Data Preparation (Split & Purge) ──────────────────────────────
    # Ensures data/L2/labelled/train and val exist to prevent leakage.
    labelled_dir = Path(get_labelled_dir(config))
    train_dir = labelled_dir / "train"
    
    success = run_phase(
        name="Data Split & Purge Guard",
        script_path="src/cloud/base_model/treino/split_dataset.py",
        check_exists=str(train_dir),
        force_retrain=force_retrain
    )
    if not success and not skip_qa_on_fail: sys.exit(1)

    # ── FASE 1: Foundation Optuna ──────────────────────────────────────────────
    # Calls the refactored run_foundation.py
    success = run_phase(
        name=f"Foundation Optuna ({n_trials_base} Trials | {epochs} Epochs | ESP: {patience})",
        script_path="src/cloud/base_model/otimizacao/run_foundation.py",
        check_exists=best_base_model,
        force_retrain=force_retrain
    )
    if not success and not skip_qa_on_fail: sys.exit(1)
    
    if manage_gpu: free_memory()
    
    # ── Verify Pipeline Flow Flags ─────────────────────────────────────────────
    spec_cfg = config.get('training', {}).get('specialization_weights', {})
    run_specialized = spec_cfg.get('run_specialized_after', True)
    run_auditor     = spec_cfg.get('run_auditor_after', True)

    # ── FASE 2: Specialist ─────────────────────────────────────────────────────
    if not run_specialized:
        logger.warning("🛑 PARADA PROGRAMADA: 'run_specialized_after' esta FALSE no master_config.yaml. Pulando treinamento do Especialista.")
    else:
        # Auto-detect: K-Fold OOF (Engorda Total) vs Legado (Holdout 80/20)
        kfold_cfg     = config.get('pre_processing', {}).get('kfold', {})
        kfold_enabled = kfold_cfg.get('enabled', False)
        oof_check     = str(mod_dir / kfold_cfg.get('oof_output_dir', 'SPECIALIST') / 'full_oof.parquet')

        if kfold_enabled:
            n_splits = kfold_cfg.get('n_splits', 5)
            gap = kfold_cfg.get('gap_minutes', 15)
            logger.info(f"🔁 K-Fold Mode ativado (kfold.enabled=true) → Executando {n_splits}-Fold Purged K-Fold Specialist")
            success = run_phase(
                name=f"K-Fold Specialist OOF ({n_splits} Folds + Purge {gap}min)",
                script_path="src/cloud/base_model/treino/run_kfold_specialist.py",
                check_exists=oof_check,
                force_retrain=force_retrain
            )
        else:
            n_trials_spec = opt_cfg.get('n_trials_specialist', 5)
            logger.info("📂 Legado Mode (kfold.enabled=false) → Executando Specialist Optuna (Holdout 80/20)")
            success = run_phase(
                name=f"Specialist Optuna ({n_trials_spec} Trials | Symmetric Delta)",
                script_path="src/cloud/base_model/treino/run_specialization.py",
                check_exists=best_spec_model,
                force_retrain=force_retrain
            )
        if not success and not skip_qa_on_fail: sys.exit(1)

        if manage_gpu: free_memory()

    # ── FASE 3: Auditor (Meta-Labeling & XGBoost) ──────────────────────────────
    if not run_auditor:
        logger.warning("🛑 PARADA PROGRAMADA: 'run_auditor_after' esta FALSE no master_config.yaml.")
        logger.info("   ↳ Pulando Fase Auditor. As predições OOF do Especialista foram geradas, mas o Juiz nao sera treinado.")
    else:
        # Auditor Requirements Check
        kfold_cfg     = config.get('pre_processing', {}).get('kfold', {})
        kfold_enabled = kfold_cfg.get('enabled', False)
        oof_check     = str(mod_dir / kfold_cfg.get('oof_output_dir', 'SPECIALIST') / 'full_oof.parquet')
        
        # Check if we have what we need
        base_exists = Path(best_base_model).exists()
        
        if kfold_enabled:
            # For K-Fold, we need base model + full_oof.parquet
            spec_signal_exists = Path(oof_check).exists()
            req_msg = f"Requeridos: Base Model ({best_base_model}) e Specialist OOF ({oof_check})"
        else:
            # For Legacy, we need base model + specialist model
            spec_signal_exists = Path(best_spec_model).exists()
            req_msg = f"Requeridos: Base Model ({best_base_model}) e Specialist Model ({best_spec_model})"

        if not base_exists or not spec_signal_exists:
            logger.error(f"❌ Requisitos do Auditor não encontrados! {req_msg}")
            if not skip_qa_on_fail: sys.exit(1)
        else:
            logger.info(f"🔍 Requisitos do Auditor carregados OK. Engatilhando Auditor...")
            
            # Auditor Preprocessing (Alpha Sensors)
            if not run_phase("Auditor Preprocessing (Context generation)", "src/cloud/auditor_model/auditor_preprocessing.py", force_retrain=force_retrain):
                sys.exit(1)
            
            # Auditor Labelling (Cross-Inference)
            if not run_phase("Auditor Labelling (Fused Logits + Sinais OOF)", "src/cloud/auditor_model/auditor_labelling.py", force_retrain=force_retrain):
                sys.exit(1)
            
            if manage_gpu: free_memory()
            
            # Auditor XGBoost Training (Dynamic F-Beta Threshold)
            if not run_phase("Auditor XGBoost (Dynamic Thresholding)", "src/cloud/auditor_model/train_xgboost.py", check_exists=auditor_model, force_retrain=force_retrain):
                sys.exit(1)
            
        if manage_gpu: free_memory()
        
    # ── FASE 3.5: Geração de Logs QA (OOF Health Check) ───────────────────────
    logger.info("="*60)
    logger.info("🩺 INICIANDO AVALIAÇÃO DE SAÚDE (QA) OOF 🩺")
    run_phase("Health QA Generation (Target Balance & NaNs)", "src/cloud/base_model/utils/qa_generator.py", force_retrain=True)
    
    # ── FASE 4: Final Transfer ────────────────────────────────────────────────
    logger.info("="*60)
    logger.info("📦 INICIANDO TRANSFERENCIA INTEGRAL (QA LOGS E MODELOS) 📦")
    
    log_filename = "run_manager.log"
    for handler in logger.handlers:
        if isinstance(handler, logging.FileHandler):
            log_filename = Path(handler.baseFilename).name
            break
            
    try:
        env = os.environ.copy()
        env["QUIET_LOGGING"] = "1"
        # Adjusted transfer call
        subprocess.run([sys.executable, "src/cloud/base_model/utils/transfer.py", log_filename, "all"], check=True, env=env)
        logger.info("✅ PIPELINE 100% EXECUTADO E SINCRONIZADO NO GOOGLE DRIVE.")
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ Transfer Failed: {e}")

if __name__ == "__main__":
    main()
