import os
import sys
import subprocess
import yaml
import logging
from pathlib import Path
import gc
from datetime import datetime

# Add project root to path
project_root = str(Path(__file__).parents[4])
if project_root not in sys.path:
    sys.path.append(project_root)

from src.cloud.base_model.utils.logging_utils import setup_logger

logger = logging.getLogger(__name__)

def free_memory():
    """Implements aggressive garbage collection to prevent VRAM spikes across phases."""
    logger.info("🧹 Initiating deep memory sweep (gc.collect and torch.cuda.empty_cache)...")
    gc.collect()
    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            logger.info("  ↳ CUDA VRAM cache cleared.")
    except ImportError:
        pass

def generate_health_log(phase_name, log_filename):
    """Stub function. In reality, QA logs will be generated by the Pytest routines or directly inside the labelling/training loops."""
    pass

def run_phase(name, script_path, check_exists=None, force_retrain=True):
    """
    Executes a phase via subprocess. 
    If check_exists is provided and force_retrain is False, checks if the target file exists to skip the phase.
    """
    logger.info("="*60)
    logger.info(f"🚀 INICIANDO FASE: {name}")
    logger.info("="*60)
    
    if not force_retrain and check_exists:
        # Checkpoint logic
        target_path = Path(check_exists)
        if target_path.exists():
            logger.info(f"⏭️ CHECKPOINT ENCONTRADO: {target_path.name} ja existe. Pulando {name} (force_full_retrain=False).")
            return True
            
    env = os.environ.copy()
    env["QUIET_LOGGING"] = "1"
    
    try:
        # v4.9: Stream subprocess output directly to the manager's logger
        # This ensures all terminal output is also saved to the run_manager logs
        process = subprocess.Popen(
            [sys.executable, script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env=env,
            bufsize=1,
            universal_newlines=True
        )
        
        # Read output in real-time
        if process.stdout:
            for line in process.stdout:
                line = line.rstrip()
                if not line: continue
                
                # v4.9.3: Back to clean format (no phase prefix, no TQDM noise)
                # Filter TQDM progress bars
                if any(bar_char in line for bar_char in ['it/s', '%|']) and '|' in line:
                    continue
                
                # Log exactly as it comes (Terminal style)
                logger.info(line)
        
        process.wait()
        
        if process.returncode == 0:
            logger.info(f"✅ FASE CONCLUIDA: {name}")
            return True
        else:
            logger.error(f"❌ FASE FALHOU: {name} (Exit Code: {process.returncode})")
            return False
    except Exception as e:
        logger.error(f"❌ ERRO AO EXECUTAR FASE: {name} | {e}")
        return False

def main():
    setup_logger("run_manager", "")
    
    # ── Session Start Marker (v4.9) ──────────────────────────────────────────
    logger.info("=" * 60)
    logger.info(f"🚀 INICIANDO NOVA SESSÃO DO PIPELINE: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info("=" * 60)
    
    # Load config
    master_cfg_path = Path("src/cloud/base_model/configs/master_config.yaml")
    with open(master_cfg_path, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
        
    ctrl = config.get('pipeline_control', {})
    force_retrain = ctrl.get('force_full_retrain', True)
    skip_qa_on_fail = ctrl.get('skip_qa_on_failure', False)
    manage_gpu = ctrl.get('gpu_memory_management', True)
    paths = config.get('pipeline_paths', {})
    
    from src.cloud.base_model.utils.path_utils import get_drive_session_path, resolve_local_drive
    mod_dir = resolve_local_drive(Path(get_drive_session_path("MODELOS", config)))
    
    best_base_macro = mod_dir / paths.get('best_tcn_lstm_model', 'BASE_MODEL/best_tcn_lstm.pt')
    best_base_dir   = mod_dir / paths.get('best_tcn_lstm_dir_model', 'BASE_MODEL/best_tcn_lstm_dir.pt')
    
    # Define o modelo base principal de acordo com a estratégia de seleção
    use_dir_strategy = config.get('training', {}).get('specialization_weights', {}).get('use_best_f1_dir', True)
    primary_base = best_base_dir if use_dir_strategy else best_base_macro
    fallback_base = best_base_macro if use_dir_strategy else best_base_dir
    
    best_spec_model = str(mod_dir / paths.get('best_specialized_model', 'BASE_MODEL/test.pt'))
    auditor_model   = str(mod_dir / paths.get('auditor_model', 'AUDITOR/auditor_xgboost.json'))
    
    # QA logs Directory Generation
    qa_path = Path("logs/QA")
    qa_path.mkdir(parents=True, exist_ok=True)
    
    opt_cfg = config.get('optimization', {})
    search_space = opt_cfg.get('search_space', {})
    n_trials_base = opt_cfg.get('n_trials', 100)
    epochs = search_space.get('epochs', 50)
    patience = search_space.get('early_stopping_patience', 4)
    
    # ── FASE 1: Foundation Optuna ──────────────────────────────────────────────
    # Recalculate paths before phase to allow mid-run changes in YAML
    mod_dir = resolve_local_drive(Path(get_drive_session_path("MODELOS", config)))
    best_base_macro = mod_dir / paths.get('best_tcn_lstm_model', 'BASE_MODEL/best_tcn_lstm.pt')
    best_base_dir   = mod_dir / paths.get('best_tcn_lstm_dir_model', 'BASE_MODEL/best_tcn_lstm_dir.pt')
    
    # Check exists is now smart: if ANY base model exists, we can skip/continue
    any_base_exists = best_base_macro.exists() or best_base_dir.exists()

    success = run_phase(
        name=f"Foundation Optuna ({n_trials_base} Trials | {epochs} Epochs | ESP: {patience})",
        script_path="src/cloud/base_model/otimizacao/run_foundation.py",
        check_exists=str(best_base_macro) if not any_base_exists else None, # Skip check if any exists
        force_retrain=force_retrain
    )
    if not success and not skip_qa_on_fail: sys.exit(1)
    
    if manage_gpu: free_memory()
    
    # ── Verify Pipeline Flow Flags ─────────────────────────────────────────────
    spec_cfg = config.get('training', {}).get('specialization_weights', {})
    run_specialized = spec_cfg.get('run_specialized_after', True)
    run_auditor     = spec_cfg.get('run_auditor_after', True)

    # ── FASE 2: Specialist ─────────────────────────────────────────────────────
    if not run_specialized:
        logger.warning("🛑 PARADA PROGRAMADA: 'run_specialized_after' esta FALSE no master_config.yaml. Pulando treinamento do Especialista.")
    else:
        # Auto-detect: K-Fold OOF (Engorda Total) vs Legado (Holdout 80/20)
        kfold_cfg     = config.get('pre_processing', {}).get('kfold', {})
        kfold_enabled = kfold_cfg.get('enabled', False)
        oof_check     = str(mod_dir / kfold_cfg.get('oof_output_dir', 'SPECIALIST') / 'full_oof.parquet')

        if kfold_enabled:
            n_splits = kfold_cfg.get('n_splits', 5)
            # Sniper Dynamic Purge Logic (Horizon + 1)
            h_min = config.get('pre_processing', {}).get('labelling', {}).get('horizon_minutes', 15)
            p_min = kfold_cfg.get('purge_minutes', 0)
            p_final = (h_min + 1) if p_min <= 0 else p_min
            
            logger.info(f"🔁 K-Fold Mode ativado (kfold.enabled=true) | Executando {n_splits}-Fold Purged K-Fold Specialist")
            success = run_phase(
                name=f"K-Fold Specialist OOF ({n_splits} Folds + Purge {p_final}min)",
                script_path="src/cloud/base_model/treino/run_kfold_specialist.py",
                check_exists=oof_check,
                force_retrain=force_retrain
            )
        else:
            n_trials_spec = opt_cfg.get('n_trials_specialist', 5)
            logger.info("📂 Legado Mode (kfold.enabled=false) → Executando Specialist Optuna (Holdout 80/20)")
            success = run_phase(
                name=f"Specialist Optuna ({n_trials_spec} Trials | Symmetric Delta)",
                script_path="src/cloud/base_model/treino/run_specialization.py",
                check_exists=best_spec_model,
                force_retrain=force_retrain
            )
        if not success and not skip_qa_on_fail: sys.exit(1)

        if manage_gpu: free_memory()

    # ── FASE 3: Auditor (Meta-Labeling & XGBoost) ──────────────────────────────
    if not run_auditor:
        logger.warning("🛑 PARADA PROGRAMADA: 'run_auditor_after' esta FALSE no master_config.yaml.")
        logger.info("   ↳ Pulando Fase Auditor. As predições OOF do Especialista foram geradas, mas o Juiz nao sera treinado.")
    else:
        # Recalcula caminhos: Se você mudou o threshold no YAML durante o treino do Especialista, 
        # o Manager agora vai detectar a nova pasta automaticamente aqui.
        from src.cloud.base_model.utils.path_utils import get_drive_session_path, resolve_local_drive
        mod_dir = resolve_local_drive(Path(get_drive_session_path("MODELOS", config)))
        
        # Auditor Requirements Check logic
        kfold_cfg     = config.get('pre_processing', {}).get('kfold', {})
        kfold_enabled = kfold_cfg.get('enabled', False)
        oof_check     = str(mod_dir / kfold_cfg.get('oof_output_dir', 'SPECIALIST') / 'full_oof.parquet')
        
        # No Auditor, precisamos da DNN de Base e do Sinal OOF do Especialista
        active_base_path = primary_base if primary_base.exists() else (fallback_base if fallback_base.exists() else None)
        base_exists = active_base_path is not None
        
        if kfold_enabled:
            # Para K-Fold, precisamos: modelo base (qualquer um dos dois) + full_oof.parquet
            spec_signal_exists = Path(oof_check).exists()
            req_msg = f"Base Model (Macro ou Dir) e Specialist OOF ({oof_check})"
        else:
            spec_signal_exists = Path(best_spec_model).exists()
            req_msg = f"Base Model e Specialist Model"

        if not base_exists:
            logger.error(f"❌ MODELO BASE AUSENTE CERIFIQUE")
            logger.error(f"   ↳ Verificado em: {mod_dir}")
            if not skip_qa_on_fail: sys.exit(1)
            
        if not spec_signal_exists:
            logger.error(f"❌ SINAL OOF AUSENTE CERIFIQUE")
            logger.error(f"   ↳ Procurado em: {oof_check}")
            if not skip_qa_on_fail: sys.exit(1)

        logger.info(f"🔍 Auditor Requirements OK. Usando Base Model: {active_base_path.name}")

            
        # Auditor Preprocessing (Alpha Sensors)
        if not run_phase("Auditor Preprocessing (Context generation)", "src/cloud/auditor_model/auditor_preprocessing.py", force_retrain=force_retrain):
            sys.exit(1)
        
        # Auditor Labelling (Cross-Inference)
        # Force retrain para garantir que o fusion data seja gerado com os novos thresholds
        if not run_phase("Auditor Labelling (Fused Logits + Sinais OOF)", "src/cloud/auditor_model/auditor_labelling.py", force_retrain=True):
            logger.error("❌ Falha critica no Auditor Labelling! Abortando.")
            sys.exit(1)
        
        if manage_gpu: free_memory()
        
        # Auditor XGBoost Training (Dynamic F-Beta Threshold)
        if not run_phase("Auditor XGBoost (Dynamic Thresholding)", "src/cloud/auditor_model/train_xgboost.py", check_exists=auditor_model, force_retrain=force_retrain):
            sys.exit(1)
            
        if manage_gpu: free_memory()
        
    # ── FASE 3.5: Geração de Logs QA (OOF Health Check) ───────────────────────
    logger.info("="*60)
    logger.info("🩺 INICIANDO AVALIAÇÃO DE SAÚDE (QA) OOF 🩺")
    run_phase("Health QA Generation (Target Balance & NaNs)", "src/cloud/base_model/utils/qa_generator.py", force_retrain=True)
    
    # ── FASE 4: Final Transfer ────────────────────────────────────────────────
    logger.info("="*60)
    logger.info("📦 INICIANDO TRANSFERENCIA INTEGRAL (QA LOGS E MODELOS) 📦")
    
    log_filename = "run_manager.log"
    for handler in logger.handlers:
        if isinstance(handler, logging.FileHandler):
            log_filename = Path(handler.baseFilename).name
            break
            
    try:
        env = os.environ.copy()
        env["QUIET_LOGGING"] = "1"
        # Adjusted transfer call
        subprocess.run([sys.executable, "src/cloud/base_model/utils/transfer.py", log_filename, "all"], check=True, env=env)
        logger.info("✅ PIPELINE 100% EXECUTADO E SINCRONIZADO NO GOOGLE DRIVE.")
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ Transfer Failed: {e}")

if __name__ == "__main__":
    main()
