import os
import sys
import subprocess
import yaml
import logging
from pathlib import Path
import gc

# Add project root to path
project_root = str(Path(__file__).parents[4])
if project_root not in sys.path:
    sys.path.append(project_root)

from src.cloud.base_model.utils.logging_utils import setup_logger

logger = logging.getLogger(__name__)

def free_memory():
    """Implements aggressive garbage collection to prevent VRAM spikes across phases."""
    logger.info("🧹 Initiating deep memory sweep (gc.collect and torch.cuda.empty_cache)...")
    gc.collect()
    try:
        import torch
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            logger.info("  ↳ CUDA VRAM cache cleared.")
    except ImportError:
        pass

def generate_health_log(phase_name, log_filename):
    """Stub function. In reality, QA logs will be generated by the Pytest routines or directly inside the labelling/training loops."""
    pass

def run_phase(name, script_path, check_exists=None, force_retrain=True):
    """
    Executes a phase via subprocess. 
    If check_exists is provided and force_retrain is False, checks if the target file exists to skip the phase.
    """
    logger.info("="*60)
    logger.info(f"🚀 INICIANDO FASE: {name}")
    logger.info("="*60)
    
    if not force_retrain and check_exists:
        # Checkpoint logic
        target_path = Path(check_exists)
        if target_path.exists():
            logger.info(f"⏭️ CHECKPOINT ENCONTRADO: {target_path.name} ja existe. Pulando {name} (force_full_retrain=False).")
            return True
            
    env = os.environ.copy()
    env["QUIET_LOGGING"] = "1"
    
    try:
        subprocess.run([sys.executable, script_path], check=True, env=env)
        logger.info(f"✅ FASE CONCLUIDA: {name}")
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ FASE FALHOU: {name}. Command: {e.cmd}")
        return False

def main():
    setup_logger("run_manager", "")
    
    # Load config
    master_cfg_path = Path("src/cloud/base_model/configs/master_config.yaml")
    with open(master_cfg_path, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
        
    ctrl = config.get('pipeline_control', {})
    force_retrain = ctrl.get('force_full_retrain', True)
    skip_qa_on_fail = ctrl.get('skip_qa_on_failure', False)
    manage_gpu = ctrl.get('gpu_memory_management', True)
    
    paths = config.get('pipeline_paths', {})
    best_base_model = paths.get('best_tcn_lstm_model', 'data/models/best_tcn_lstm.pt')
    best_spec_model = paths.get('best_specialized_model', 'data/models/best_specialized_model.pt')
    auditor_model   = paths.get('auditor_model', 'data/models/auditor_xgboost.json')
    
    # QA logs Directory Generation
    qa_path = Path("logs/QA")
    qa_path.mkdir(parents=True, exist_ok=True)
    
    # ── FASE 1: Foundation Optuna ──────────────────────────────────────────────
    # Calls the refactored run_foundation.py
    success = run_phase(
        name="Foundation Optuna (60 Trials)",
        script_path="src/cloud/base_model/otimizacao/run_foundation.py",
        check_exists=best_base_model,
        force_retrain=force_retrain
    )
    if not success and not skip_qa_on_fail: sys.exit(1)
    
    if manage_gpu: free_memory()
    
    # ── FASE 2: Specialist Optuna ──────────────────────────────────────────────
    success = run_phase(
        name="Specialist Optuna (Symmetric Delta)",
        script_path="src/cloud/base_model/treino/run_specialization.py",
        check_exists=best_spec_model,
        force_retrain=force_retrain
    )
    if not success and not skip_qa_on_fail: sys.exit(1)
    
    if manage_gpu: free_memory()
    
    # ── FASE 3: Auditor (Meta-Labeling & XGBoost) ──────────────────────────────
    # Check if models exist (OOF Condition)
    if not Path(best_base_model).exists() or not Path(best_spec_model).exists():
        logger.error(f"❌ Modelos Base ou Especialista não encontrados! Requeridos para treinar o Juiz.")
        if not skip_qa_on_fail: sys.exit(1)
    else:
        logger.info(f"🔍 Modelos Base e Especialista carregados OK. Engatilhando Auditor OOF...")
        
        # Auditor Preprocessing (Alpha Sensors)
        run_phase("Auditor Preprocessing (Context generation)", "src/cloud/auditor_model/auditor_preprocessing.py", force_retrain=force_retrain)
        
        # Auditor Labelling (Cross-Inference)
        run_phase("Auditor Labelling (Fused Logits + Sinais OOF)", "src/cloud/auditor_model/auditor_labelling.py", force_retrain=force_retrain)
        
        if manage_gpu: free_memory()
        
        # Auditor XGBoost Training (Dynamic F-Beta Threshold)
        run_phase("Auditor XGBoost (Dynamic Thresholding)", "src/cloud/auditor_model/train_xgboost.py", check_exists=auditor_model, force_retrain=force_retrain)
        
    if manage_gpu: free_memory()
    
    # ── FASE 3.5: Geração de Logs QA (OOF Health Check) ───────────────────────
    logger.info("="*60)
    logger.info("🩺 INICIANDO AVALIAÇÃO DE SAÚDE (QA) OOF 🩺")
    run_phase("Health QA Generation (Target Balance & NaNs)", "src/cloud/base_model/utils/qa_generator.py", force_retrain=True)
    
    # ── FASE 4: Final Transfer ────────────────────────────────────────────────
    logger.info("="*60)
    logger.info("📦 INICIANDO TRANSFERENCIA INTEGRAL (QA LOGS E MODELOS) 📦")
    
    log_filename = "run_manager.log"
    for handler in logger.handlers:
        if isinstance(handler, logging.FileHandler):
            log_filename = Path(handler.baseFilename).name
            break
            
    try:
        env = os.environ.copy()
        env["QUIET_LOGGING"] = "1"
        # Adjusted transfer call
        subprocess.run([sys.executable, "src/cloud/base_model/utils/transfer.py", log_filename, "all"], check=True, env=env)
        logger.info("✅ PIPELINE 100% EXECUTADO E SINCRONIZADO NO GOOGLE DRIVE.")
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ Transfer Failed: {e}")

if __name__ == "__main__":
    main()
